### ISSUE TITLE
Interpretation of tr.first/tr.second

### ISSUE THREAD

**Issue by kvittingseerup** [guigolab/sQTLseekeR2#7]
According to [this](https://github.com/guigolab/sQTLseekeR/blob/master/man/sqtl.seeker.Rd) the tr.first/tr.second indicate the transcripts which change the most (meaning in opposite patterns right?).

Does the tr.first/tr.second assignment also enable interpretation of which transcript is used more in the REF/REF and which one is used more in ALT/ALT or will be assignment to tr.first/tr.second be unrelated to genotype?

Cheers
Kristoffer

**Comment by dgarrimar** [comment]
Sorry for the late reply,

exactly, `tr.first` and `tr.second` are those isoforms that change the most (in opposite directions) between genotypes, but these do not give information about in which genotypes they are used more/less.
